stages:
  - test # All jobs related for testing such as Unit Test
  - build # All jobs related for building app for iOS and Android
  - deploy

before_script:
  - export PATH="$PATH:/Users/ronalddelacruz/development/flutter/bin"
    
flutter_test: # Name of the lane
  stage: test # type of stage
  script:
    - flutter test # Run Flutter test
  tags:
    - flutter # Tags for runner


flutter_build_android:
  stage: build
  before_script:
    - export PATH="$PATH:/Users/ronalddelacruz/development/flutter/bin"
    - flutter channel stable
    - cd android
    - bundle install --deployment
  script:
    - bundle exec fastlane build
  artifacts:
    paths:
      - build/app/outputs/apk/release/app-arm64-v8a-release.apk
  tags:
    - flutter
  only:
    - develop


deploy_android:
  stage: deploy
  before_script:
    - export PATH="$PATH:/Users/ronalddelacruz/development/flutter/bin"
    - cd android
    - bundle install --deployment
  dependencies:
    - flutter_build_android
  script:
    - bundle exec fastlane deploy
  tags:
    - flutter
  only:
    - develop


flutter_build_ios:
  stage: build
  before_script:
    - export PATH="$PATH:/Users/ronalddelacruz/development/flutter/bin"
    - flutter channel stable
    - cd ios
    - bundle install --deployment
  script:
    - bundle exec fastlane build
  artifacts:
    paths:
      - /build/Runner.ipa
  tags:
    - flutter
  only:
    - develop

deploy_ios:
  stage: deploy
  before_script:
    - export PATH="$PATH:/Users/ronalddelacruz/development/flutter/bin"
    - cd ios
    - bundle install --deployment
  dependencies:
    - flutter_build_ios
  script:
    - bundle exec fastlane deploy
  tags:
    - flutter
  only:
    - develop

flutter_build_web:
  stage: build
  before_script:
    - export PATH="$PATH:/Users/ronalddelacruz/development/flutter/bin"
    - flutter channel beta
  script:
    - flutter build web
  artifacts:
    paths:
      - build/web
  tags:
    - flutter
  only:
    - develop

deploy_web:
  image: node:12.13.0-alpine
  stage: deploy
  before_script:
    - export PATH="$PATH:/Users/ronalddelacruz/development/flutter/bin"
    - npm i -g firebase-tools
  dependencies:
    - flutter_build_web
  script:
    - flutter use staging
    - firebase deploy --token $FIREBASE_TOKEN
  only:
    - develop
