stages:
  - analyze
  - test # All jobs related for testing such as Unit Test
  - build_web
  - deploy_web
  - build_android
  - deploy_android
  - build_ios
  - deploy_ios

flutter_analyze: # Name of the lane
  stage: analyze # type of stage
  script:
    - flutter analyze # Run Flutter test
  tags:
    - flutter # Tags for runner
    
flutter_test: 
  stage: test 
  script:
    - flutter test --coverage # Generates the lcov file
    - lcov --list coverage/lcov.info
    - genhtml coverage/lcov.info --output=coverage # generates the 
  artifacts:
    paths:
      - coverage
  tags:
    - flutter 

flutter_build_web:
  stage: build_web
  before_script:
    - flutter channel beta
  script:
    - flutter config --enable-web
    - flutter build web
  artifacts:
    paths:
      - build/web
  tags:
    - flutter
  only:
    - develop

deploy_web:
  stage: deploy_web
  before_script:
    - npm i -g firebase-tools
  dependencies:
    - flutter_build_web
  script:
    - firebase use staging
    - firebase deploy --token $FIREBASE_TOKEN
  only:
    - develop

flutter_build_android:
  stage: build_android
  before_script:
    - flutter channel stable
    - cd android
    - bundle install --deployment
  script:
    - bundle exec fastlane build
  artifacts:
    paths:
      - build/app/outputs/apk/release/app-arm64-v8a-release.apk
  tags:
    - flutter
  only:
    - develop

deploy_android:
  stage: deploy_android
  before_script:
    - cd android
    - bundle install --deployment
  dependencies:
    - flutter_build_android
  script:
    - bundle exec fastlane deploy
  tags:
    - flutter
  only:
    - develop

flutter_build_ios:
  stage: build_ios
  before_script:
    - flutter channel stable
    - cd ios
    - bundle install --deployment
  script:
    - bundle exec fastlane build
  artifacts:
    paths:
      - /Users/macmini/builds/a96d4856/0/thebrewery/flutter/globeone_poc/ios/build/Runner.ipa
  tags:
    - flutter
  only:
    - develop

deploy_ios:
  stage: deploy_ios
  before_script:
    - cd ios
    - bundle install --deployment
  dependencies:
    - flutter_build_ios
  script:
    - bundle exec fastlane deploy
  tags:
    - flutter
  only:
    - develop


