name: globe_one_poc_project
description: A GlobeOne POC using flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^3.2.0
  graphql_flutter: ^3.0.0
  shared_preferences: ^0.5.6+2
  intl: ^0.16.1


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_launcher_name:
  name: "GlobeOne POC"

flutter_icons:
  image_path: "assets/icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    # assets-generator-begin
    # assets/*
    - assets/duck_placeholder.png
    - assets/icon.png
    - assets/ic_globe_banner.png
    # assets-generator-end
  fonts:
    - family: FSElliotPro
      fonts:
        - asset: assets/fonts/FSElloitPro/FS-Elliot-Pro-Bold.otf
        - asset: assets/fonts/FSElloitPro/FS-Elliot-Pro-Italic.otf
        - asset: assets/fonts/FSElloitPro/FS-Elliot-Pro-Regular.otf
          style: italic
