name: finished_notes_firebase_ddd_course
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.9.0-dev.6
  freezed_annotation: ^0.7.1
  uuid: ^2.0.4
  flutter_bloc: ^3.2.0
  auto_route: ^0.3.1
  get_it: ^3.1.0
  meta: ^1.1.8
  firebase_core: ^0.4.3+3
  firebase_auth: ^0.15.4
  google_sign_in: ^4.1.1
  cloud_firestore: ^0.13.3
  injectable: ^0.3.0
  flushbar: ^1.9.1
  json_annotation: ^3.0.1
  styled_widget: ^0.1.1
  flutter_hooks: ^0.8.0
  time: ^1.2.0
  kt_dart: ^0.7.0
  rxdart: ^0.23.1
  reorderables: ^0.2.12
  provider: ^4.0.4
  implicitly_animated_reorderable_list: ^0.1.9
  flutter_slidable: ^0.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.1.1
  build_runner:
  freezed: ^0.9.2
  auto_route_generator: ^0.3.2
  injectable_generator: ^0.3.2
  json_serializable: ^3.2.5
  flutter_launcher_name: ^0.0.1
  flutter_launcher_icons: ^0.7.4

flutter_launcher_name:
  name: "GlobeOne POC"

flutter_icons:
  image_path: "assets/icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    # assets-generator-begin
    # assets/*
    - assets/icon.png
    # assets-generator-end
