name: globe_one_poc_project
description: A GlobeOne POC using flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^3.2.0
  shared_preferences: ^0.5.6+2
  http: ^0.12.0+4
  intl: ^0.16.1
  dartz: ^0.9.0-dev.6
  equatable: ^1.0.0
  sembast: ^2.4.2
  path_provider: ^1.6.7
  sembast_web: '>=1.1.0-dev.3'
  cached_network_image: ^2.1.0+1
  url_launcher: ^5.4.2
  dio: ^3.0.9
  universal_io: ^1.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:

  mockito: ^4.1.1

flutter_launcher_name:
  name: "GlobeOne POC"

flutter_icons:
  image_path: "assets/icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/duck/
    # assets-generator-begin
    # assets/*
    - assets/duck_placeholder.png
    - assets/ic_globe_banner.png
    - assets/icon.png
    - assets/rest_of_screen.png
    # assets/images/*
    - assets/images/globelogo.png
    - assets/images/mobiletopbanner.png
    - assets/images/topbanner.png
    - assets/images/user.png
    - assets/images/webspeedlimit.png
    # assets-generator-end
  
  fonts:
    - family: FSElliotPro
      fonts:
        - asset: assets/font/FS-Elliot-Pro-Regular.otf
        - asset: assets/font/FS-Elliot-Pro-Light.otf
          weight: 100
        - asset: assets/font/FS-Elliot-Pro-Bold.otf
          weight: 700


