# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)
platform :android do
  desc "Build a Flutter apk"
  lane :build do
    Dir.chdir("../..") do
      sh "flutter packages get"
      sh "flutter clean"
      sh "flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi"
    end
  end
  desc "Submit a new Aplha Build to AppCenter"
  lane :deploy do
  if File.exist?(File.dirname(__FILE__) + "./../build/app/outputs/apk/release/app-arm64-v8a-release.apk")
    appcenter_upload(
      api_token: "62330455c2dbab4f6bb508ad7fb256498a616f0f", # Your secret api token from app center
      owner_name: "globeone_poc", # Your username on AppCenter
      owner_type: "organization",
      app_name: "globeone_poc_android", # Your AppCenter name
      apk: "../build/app/outputs/apk/release/app-arm64-v8a-release.apk",
    )
    else
      UI.message('Unable to find apk')
    end
  end
end
